---
abstract: 'Build Your Application Instance Programatically'
author:
  - 'Daisuke Maki C<< <daisuke@endeworks.jp> >>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CatalystX-AppBuilder
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst: 5.80024
  Moose: 0
  namespace::clean: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/lestrrat/CatalystX-AppBuilder.git
version: 0.00009
